created: 2026-10-09T23:18:55.381Z
updated: 2026-10-09T23:18:55.596Z
update_count: 2
last_field: diagram
kind: nested-class
title: source-review
children:
  - auto-flagged
  - auto-verified
  - human-reviewed
  - quarantined
  - unreviewed
parentPath: []
