created: 2026-10-09T00:32:05.948Z
updated: 2026-10-09T00:32:06.827Z
update_count: 3
last_field: concern
kind: nested-class
title: update-states
children:
  - marker-written
  - result-failed
  - result-rolled-back
  - result-running
  - result-succeeded
  - result-up-to-date
parentPath: []
