created: 2026-10-05 03:34:23.179000+00:00
updated: 2026-10-05 03:34:23.318000+00:00
update_count: 2
last_field: diagram
kind: nested-class
title: paid-answer-pipeline
children:
- answer-validation
parentPath: []
