created: 2026-10-08T22:02:24.639Z
updated: 2026-10-08T22:02:24.796Z
update_count: 2
last_field: diagram
kind: nested-class
title: ingest
children:
  - converter
  - ocr
  - pdf
  - quarantine
  - reuse
  - revision
parentPath: []
