created: 2026-10-05 09:51:21.768000+00:00
updated: 2026-10-05 09:51:21.896000+00:00
update_count: 2
last_field: diagram
kind: nested-class
title: corpus-pipeline
children:
- ocr-merge
parentPath:
- offline-pipelines
