created: 2026-10-05T09:51:24.795Z
updated: 2026-10-05T09:51:24.796Z
update_count: 1
last_field: description
kind: nested-class
title: activation-gate
children: []
parentPath:
  - offline-pipelines
  - comparison-runner
