created: 2026-10-08T22:02:13.717Z
updated: 2026-10-08T22:02:14.007Z
update_count: 3
last_field: note
kind: nested-class
title: evaluation
children:
  - activation
  - compare
  - drafting
  - gold
  - maintenance
  - runs
  - serving
parentPath: []
