created: 2026-10-05T03:34:25.621Z
updated: 2026-10-05T04:06:32.977Z
update_count: 3
last_field: diagram
kind: nested-class
title: serving-activation
children:
  - activated-run
  - hybrid-without-reranker
  - keyword-default
  - keyword-fallback
parentPath: []
