created: 2026-10-05T09:51:22.706Z
updated: 2026-10-05T09:51:22.707Z
update_count: 1
last_field: description
kind: nested-class
title: fidelity-check
children: []
parentPath:
  - offline-pipelines
  - corpus-pipeline
