created: 2026-10-08T21:41:47.341Z
updated: 2026-10-08T21:41:47.592Z
update_count: 3
last_field: context
kind: nested-class
title: web
children:
  - ask
  - dataset
  - gate
  - settings
  - verify
parentPath: []
