created: 2026-10-06T07:31:37.565Z
updated: 2026-10-06T07:31:37.736Z
update_count: 2
last_field: diagram
kind: nested-class
title: attempt-states
children:
  - dispatching
  - reconciled
  - released
  - reserved
  - settled
  - unknown
parentPath: []
