created: 2026-10-08T22:02:20.980Z
updated: 2026-10-08T22:02:21.102Z
update_count: 2
last_field: diagram
kind: nested-class
title: attempt
children:
  - dispatching
  - reconciled
  - released
  - reserved
  - settled
  - unknown
parentPath: []
