created: 2026-10-08T22:02:12.499Z
updated: 2026-10-08T22:02:12.628Z
update_count: 2
last_field: diagram
kind: nested-class
title: gateway
children:
  - caller
  - embed
  - ledger
  - owner
  - tracing
  - transport
parentPath: []
