created: 2026-10-05T09:51:22.025Z
updated: 2026-10-05T09:51:22.025Z
update_count: 1
last_field: description
kind: nested-class
title: manifest-import
children: []
parentPath:
  - offline-pipelines
  - corpus-pipeline
