created: 2026-10-04 13:34:42.449000+00:00
updated: 2026-10-09T02:46:21.007Z
update_count: 17
last_field: diagram
kind: nested-class
title: http-api
children:
  - account-routes
  - ask-routes
  - auth-routes
  - dataset-routes
  - lifespan
  - route-groups
  - session-middleware
  - static-export
  - stream-route
  - verify-routes
parentPath: []
