created: 2026-10-06T08:28:47.686Z
updated: 2026-10-06T08:28:48.017Z
update_count: 3
last_field: constraint
kind: nested-class
title: web-pages
children:
  - answer-stream
  - api-client
  - app-header
  - ask-page
  - dataset-page
  - settings-page
  - verify-page
parentPath: []
