created: 2026-10-08T22:02:19.463Z
updated: 2026-10-08T22:02:19.586Z
update_count: 2
last_field: diagram
kind: nested-class
title: request
children:
  - cancelled
  - completed
  - failed
  - interrupted
  - queued
  - running
parentPath: []
