created: 2026-10-06T07:57:20.295Z
updated: 2026-10-09T23:19:02.572Z
update_count: 7
last_field: diagram
kind: nested-class
title: gold-candidate
children:
  - approved
  - draft-run
  - pending
  - rejected
  - second-review
parentPath: []
