created: 2026-10-08 21:41:51.990000+00:00
updated: 2026-10-08 21:41:52.116000+00:00
update_count: 2
last_field: diagram
kind: nested-class
title: retrieval
children:
- dense
- fusion
- lexical
- scope
parentPath: []
