created: 2026-10-06T22:40:22.515Z
updated: 2026-10-06T22:40:22.655Z
update_count: 2
last_field: diagram
kind: nested-class
title: request-states
children:
  - cancelled
  - completed
  - failed
  - interrupted
  - queued
  - running
parentPath: []
