created: 2026-10-08T22:02:16.803Z
updated: 2026-10-08T22:02:16.953Z
update_count: 2
last_field: diagram
kind: nested-class
title: paid
children:
  - checks
  - finish
  - metered
  - prepare
  - rewrite
  - validate
parentPath: []
