created: 2026-10-09T10:52:31.145Z
updated: 2026-10-09T10:52:31.285Z
update_count: 2
last_field: diagram
kind: nested-class
title: gold-states
children:
  - approved
  - pending
  - rejected
  - second-reviewed
parentPath: []
