created: 2026-10-06 07:31:43.364000+00:00
updated: 2026-10-06 07:31:44.182000+00:00
update_count: 3
last_field: note
git_commit: 80ccafa
git_branch: deploy-gcp-vm-ssh-tunnel
children:
- app-process
- systemd-unit
