created: 2026-10-05T23:55:29.570Z
updated: 2026-10-05T23:55:29.909Z
update_count: 2
last_field: diagram
kind: nested-class
title: request-status
children:
  - cancelled
  - completed
  - failed
  - interrupted
  - queued
  - running
parentPath: []
