created: 2026-10-05T04:06:32.527Z
updated: 2026-10-05T04:06:32.528Z
update_count: 1
last_field: description
kind: nested-class
title: awaiting-second-review
children: []
parentPath:
  - gold-candidate
