created: 2026-10-05 09:51:23.444000+00:00
updated: 2026-10-05T23:55:23.105Z
update_count: 4
last_field: description
kind: nested-class
title: comparison-runner
children: []
parentPath:
  - offline-pipelines
