created: 2026-10-05 09:51:23.444000+00:00
updated: 2026-10-05 09:51:23.745000+00:00
update_count: 3
last_field: constraint
kind: nested-class
title: comparison-runner
children: []
parentPath:
- offline-pipelines
