created: 2026-10-08T21:41:50.148Z
updated: 2026-10-08T21:41:50.280Z
update_count: 2
last_field: diagram
kind: nested-class
title: service
children:
  - completion
  - evidence
  - paid
  - preparation
  - resources
  - runner
parentPath: []
