created: 2026-10-07T06:24:25.129Z
updated: 2026-10-07T06:24:25.130Z
update_count: 1
last_field: description
kind: nested-class
title: maintenance-sequence
children: []
parentPath:
  - offline-pipelines
