created: 2026-10-05T21:24:09.867Z
updated: 2026-10-05T21:24:10.312Z
update_count: 2
last_field: diagram
git_commit: 797b897
git_branch: judge-set-and-maintenance
children:
  - application-mutex
  - cli-paid-commands
  - controlled-shutdown
  - gateway-lock
  - job-registry
  - uvicorn-process
