created: 2026-10-08T21:41:48.592Z
updated: 2026-10-08T21:41:48.720Z
update_count: 2
last_field: diagram
kind: nested-class
title: http
children:
  - errors
  - lifespan
  - oauth
  - routes
  - session
  - static
parentPath: []
