created: 2026-10-09T23:18:40.050Z
updated: 2026-10-09T23:18:40.053Z
update_count: 1
last_field: description
kind: nested-class
title: comparison-matrices
children: []
parentPath:
  - evaluation-suite
