created: 2026-10-05 03:34:21.317000+00:00
updated: 2026-10-07T04:46:49.366Z
update_count: 14
last_field: description
kind: nested-class
title: postgresql-store
children:
  - application-mutex
parentPath: []
